jobs:
  publish_snapshot:
    if: github.event_name == 'push' && github.repository == 'google/google-java-format'
      && github.ref == 'refs/heads/master'
    name: Publish snapshot
    needs: test-OpenJDK
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Check out repository
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        cache: maven
        distribution: zulu
        java-version: 17
        server-id: sonatype-nexus-snapshots
        server-password: CI_DEPLOY_PASSWORD
        server-username: CI_DEPLOY_USERNAME
    - continue-on-error: true
      env:
        CI_DEPLOY_PASSWORD: ${{ secrets.CI_DEPLOY_PASSWORD }}
        CI_DEPLOY_USERNAME: ${{ secrets.CI_DEPLOY_USERNAME }}
      name: Publish
      run: mvn -pl '!eclipse_plugin' source:jar deploy -B -DskipTests=true -Dinvoker.skip=true
        -Dmaven.javadoc.skip=true
  test-GraalVM:
    continue-on-error: true
    name: GraalVM on ${{ matrix.os }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Cancel previous
      uses: styfle/cancel-workflow-action@0.9.1
      with:
        access_token: ${{ github.token }}
    - continue-on-error: true
      name: Check out repository
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Set up GraalVM ${{ matrix.java }}
      uses: graalvm/setup-graalvm@v1
      with:
        cache: maven
        distribution: graalvm-community
        github-token: ${{ secrets.GITHUB_TOKEN }}
        java-version: '21'
        native-image-job-reports: 'true'
    - continue-on-error: true
      name: Native Build
      run: mvn -Pnative -DskipTests package -pl core -am
    - continue-on-error: true
      if: ${{ matrix.os != 'windows-latest' }}
      name: Native Test
      run: util/test-native.sh
    strategy:
      fail-fast: false
      matrix:
        os:
        - ubuntu-20.04
        - macos-latest
        - windows-latest
  test-OpenJDK:
    continue-on-error: ${{ matrix.experimental }}
    name: JDK ${{ matrix.java }} on ${{ matrix.os }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Cancel previous
      uses: styfle/cancel-workflow-action@0.9.1
      with:
        access_token: ${{ github.token }}
    - continue-on-error: true
      name: Check out repository
      uses: actions/checkout@v4
    - continue-on-error: true
      if: ${{ matrix.java == 'EA' }}
      name: Set up JDK ${{ matrix.java }} from jdk.java.net
      uses: oracle-actions/setup-java@v1
      with:
        release: ${{ matrix.java }}
        website: jdk.java.net
    - continue-on-error: true
      if: ${{ matrix.java != 'EA' && matrix.java != 'GraalVM' }}
      name: Set up JDK ${{ matrix.java }} from Zulu
      uses: actions/setup-java@v4
      with:
        cache: maven
        distribution: zulu
        java-version: ${{ matrix.java }}
    - continue-on-error: true
      name: Install
      run: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
      shell: bash
    - continue-on-error: true
      name: Test
      run: mvn test -B
      shell: bash
    strategy:
      fail-fast: false
      matrix:
        experimental:
        - false
        include:
        - experimental: false
          java: 21
          os: macos-latest
        - experimental: false
          java: 21
          os: windows-latest
        - experimental: true
          java: EA
          os: ubuntu-latest
        java:
        - 21
        - 17
        - 11
        os:
        - ubuntu-latest
name: CI
on:
  repository_dispatch:
    types: trigger-ga___ci.yml
